services:

  api:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8000:8000"

    environment:
      DATABASE_URL: postgresql+psycopg://shop_user:shop_password@db:5432/shop_db
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      APP_ENV: development

    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:18

    environment:
      POSTGRES_DB: shop_db
      POSTGRES_USER: shop_user
      POSTGRES_PASSWORD: shop_password

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shop_user -d shop_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: