"""add refund and returned inventory states

Revision ID: 8e9f9db327a9
Revises: ce5efe2057d1
Create Date: 2026-09-08 15:55:38.069482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e9f9db327a9'
down_revision: Union[str, Sequence[str], None] = 'ce5efe2057d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('provider_refund_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_payments_provider_refund_id'), 'payments', ['provider_refund_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_provider_refund_id'), table_name='payments')
    op.drop_column('payments', 'provider_refund_id')
    # ### end Alembic commands ###
