"""enforce one default address per user

Revision ID: 927d9eea637e
Revises: 6dd2feed9aff
Create Date: 2026-09-29 20:32:54.892351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '927d9eea637e'
down_revision: Union[str, Sequence[str], None] = '6dd2feed9aff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_one_default_address_per_user', 'addresses', ['user_id'], unique=True, postgresql_where=sa.text('is_default = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_one_default_address_per_user', table_name='addresses', postgresql_where=sa.text('is_default = true'))
    # ### end Alembic commands ###
