"""add product constraints

Revision ID: 978448ca2039
Revises: cb45fecd6a65
Create Date: 2026-08-31 14:56:03.022648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '978448ca2039'
down_revision: Union[str, Sequence[str], None] = 'cb45fecd6a65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('ck_products_price_positive', 'products', 'price > 0')
    op.create_check_constraint('ck_products_stock_non_negative', 'products', 'stock_quantity >= 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_products_stock_non_negative', 'products', type_='check')
    op.drop_constraint('ck_products_price_positive', 'products', type_='check')
    # ### end Alembic commands ###
