"""add returned inventory status

Revision ID: ce5efe2057d1
Revises: 4dd87be54d9a
Create Date: 2026-09-08 14:15:49.947058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce5efe2057d1'
down_revision: Union[str, Sequence[str], None] = '4dd87be54d9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('ck_inventory_reservation_quantity_positive', 'inventory_reservations', 'quantity > 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_inventory_reservation_quantity_positive', 'inventory_reservations', type_='check')
    # ### end Alembic commands ###
